### ISSUE TITLE
TypeError: Cannot read property 'server' of undefined

### ISSUE THREAD

**Issue by Woersty** [iobroker-community-adapters/ioBroker.worx#229]
Hallo,

ich habe heute den **npm ioBroker.worx** Adapter meiner FHEM-MQTT Installation auf dem LoxBerry aktualisiert und jetzt verbindet er sich nicht mehr. Vorher lief alles so schön. 😢 
Kann mir da jemand helfen?

Das Kommando `node LandroidSrv.js mower1` bringt:
```
/opt/landroid/fhem-landroid-s/node_modules/iobroker.worx/lib/api.js:155
        this.server = adapter.config.server
                                     ^
TypeError: Cannot read property 'server' of undefined
    at new Worx (/opt/landroid/fhem-landroid-s/node_modules/iobroker.worx/lib/api.js:155:38)
    at main (/opt/landroid/fhem-landroid-s/LandroidSrv.js:451:15)
    at Object.<anonymous> (/opt/landroid/fhem-landroid-s/LandroidSrv.js:494:3)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
 - Adapter version: 1.3.0
 - JS-Controller version: Wie auslesen? iobroker ist ja nicht installiert
 - Node version: v12.19.0

 - Operating system: LoxBerry 2.x / Raspbian GNU/Linux 10 (buster)

Vielen Dank im Voraus
Wörsty

**Comment by Woersty** [comment]
Achso, vielleicht sollte ich noch erwähnen, dass es nicht dringend ist.
Ich habe als Workaround [hier](https://github.com/iobroker-community-adapters/ioBroker.worx/blob/master/lib/api.js#L155) adapter.config.server durch "worx" ersetzt. 
Und [hier](https://github.com/iobroker-community-adapters/ioBroker.worx/blob/master/lib/api.js#L406) http durch https, was komischerweise in der 1.3.0 npm Version noch nicht drin war.
Trotzdem wäre es schön, wenn es ohne die Anpassungen gehen würde.

**Comment by MeisterTR** [comment]
fixed
