### ISSUE TITLE
Connection blocked from Worx Server -  no communication possible

### ISSUE THREAD

**Issue by notkom** [iobroker-community-adapters/ioBroker.worx#37]
No connection to the Worx server. The connection is blocked by Worx. This means that no status data can be queried.

Error message in the log:
(17345) Connection blocked from Worx, please try again in 24h
-------------------------------

**Feedback from Worx Support**

> _If you use an unofficial app, software or suite, you should uninstall it and disconnect it from the robot.  We only support the official Worx Landroid app, which you can download from the App Store / Play Store.  Most third-party apps can negatively impact server settings, so we won't support them for now.  We would like to point out that some of these apps could be classified as malicious by our security systems, which will result in the account being temporarily  blocked._ >

**Comment by MeisterTR** [comment]
yes as you read in the log you have to wait 24 hours

**Comment by notkom** [comment]
And then? I get every time the same error message in log.

At starting the worx adapter updates the objects, but only one time. 

I tried to start and use the adapter several day. Every day the same error.

**Comment by notkom** [comment]
`

2020-03-15   08:15:29.779 - info: worx.0 (22549) starting. Version 1.0.0 in   /opt/iobroker/node_modules/iobroker.worx, node: v10.19.0
--
2020-03-15 08:15:31.469 - warn: worx.0   (22549) Connection blocked from Worx, please try again in 24h
2020-03-15 08:18:23.890 - info: worx.0   (22549) Got terminate signal TERMINATE_YOURSELF
2020-03-15 08:18:23.891 - info: worx.0   (22549) cleaned everything up...
2020-03-15 08:18:23.892 - info: worx.0   (22549) terminating
2020-03-15 08:18:23.894 - info: worx.0   (22549) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
2020-03-15 08:29:56.052 - info:   host.raspberrypi "system.adapter.worx.0" enabled
2020-03-15 08:29:56.088 - info:   host.raspberrypi instance system.adapter.worx.0 started with pid 25068
2020-03-15 08:29:59.600 - info: worx.0   (25068) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.worx,   node: v10.19.0
2020-03-15 08:30:01.260 - warn: worx.0   (25068) Connection blocked from Worx, please try again in 24h
2020-03-15 08:30:42.529 - error: worx.0   (25068) uncaught exception: Cannot read property 'publish' of undefined
2020-03-15 08:30:42.530 - error: worx.0   (25068) TypeError: Cannot read property 'publish' of undefined
at Worx.sendMessage   (/opt/iobroker/node_modules/iobroker.worx/lib/api.js:278:30)
at Worx.onStateChange   (/opt/iobroker/node_modules/iobroker.worx/main.js:998:36)
at Worx.emit (events.js:198:13)
2020-03-15 08:30:42.531 - info: worx.0   (25068) cleaned everything up...
2020-03-15 08:30:42.538 - info: worx.0   (25068) terminating
2020-03-15 08:30:42.543 - info: worx.0   (25068) Terminated (NO_ERROR): Without reason
2020-03-15 08:31:15.616 - error: worx.0   (31205) adapter disabled
2020-03-15 08:31:15.636 - warn: worx.0   (31205) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason

`
