### ISSUE TITLE
Keine Verbindung zu Kress Server

### ISSUE THREAD

**Issue by Semmy100** [iobroker-community-adapters/ioBroker.worx#571]
Ich habe seit heute keine Verbindung mehr zum Kress Server.

**Comment by hsteinme** [comment]
Stell bitte den Adapter in den Debuig-Modus und zitiere hie die entsprechenden Fehlermeldungen aus der Logdatei.

**Comment by Semmy100** [comment]
So steht es im Log:

worx.0 | 2022-09-25 09:13:55.999 | error | ERROR: StatusCodeError: 404 - {"message":"Not Found","code":"404.000"}
-- | -- | -- | --
worx.0 | 2022-09-25 09:13:55.998 | error | Could not Connect to Worx Server: StatusCodeError: 404 - {"message":"Not Found","code":"404.000"}
worx.0 | 2022-09-25 09:13:55.647 | debug | Connect to worx....
worx.0 | 2022-09-25 09:13:55.645 | info | kress is selected
worx.0 | 2022-09-25 09:13:55.604 | info | starting. Version 1.6.6 in /opt/iobroker/node_modules/iobroker.worx, node: v16.17.1, js-controller: 4.0.23
worx.0 | 2022-09-25 09:13:55.062 | debug | Plugin sentry Initialize Plugin (enabled=true)
worx.0 | 2022-09-25 09:13:54.405 | debug | States connected to redis: 127.0.0.1:9000
worx.0 | 2022-09-25 09:13:54.124 | debug | States create User PubSub Client
worx.0 | 2022-09-25 09:13:54.119 | debug | States create System PubSub Client
worx.0 | 2022-09-25 09:13:53.991 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
worx.0 | 2022-09-25 09:13:53.797 | debug | Objects connected to redis: 127.0.0.1:9001
worx.0 | 2022-09-25 09:13:53.774 | debug | Objects client initialize lua scripts
worx.0 | 2022-09-25 09:13:53.346 | debug | Objects create User PubSub Client
worx.0 | 2022-09-25 09:13:53.342 | debug | Objects create System PubSub Client
worx.0 | 2022-09-25 09:13:53.335 | debug | Objects client ready ... initialize now
worx.0 | 2022-09-25 09:13:53.115 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
worx.0 | 2022-09-25 09:13:47.381 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
worx.0 | 2022-09-25 09:13:47.379 | debug | Plugin sentry destroyed
worx.0 | 2022-09-25 09:13:47.377 | info | terminating
worx.0 | 2022-09-25 09:13:47.376 | info | cleaned everything up...
worx.0 | 2022-09-25 09:13:47.373 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>

**Comment by Grothesk242** [comment]
Same issue?

https://github.com/iobroker-community-adapters/ioBroker.worx/issues/569

**Comment by Semmy100** [comment]
Sieht nach den gleichen Fehler aus!

**Comment by jayfizzle** [comment]
Beim öffnen der api urls über den Browser erhält man die identischen Fehlermeldungen wie im log, betrifft alle api's
- https://api.worxlandroid.com
- https://api.kress-robotik.com
- https://api.landxcape-services.com

![grafik](https://user-images.githubusercontent.com/40118991/192483047-ae40ffc5-8d04-4c70-8123-f614a9db5b26.png)

anscheinend wurden die API urls seitens Positec verändert.

**Comment by Subseven1983** [comment]
Gibt es bereits eine Lösung für das Problem?

**Comment by jayfizzle** [comment]
ist mir nicht bekannt, könnte eher der Adaper-Ersteller beantworten.

**Comment by TA2k** [comment]
Ich kann mir das mal anschauen

**Comment by TA2k** [comment]
Die Github version enthält ein fix für den worx login

**Comment by MubiTec** [comment]
Danke für deine Mühen!
Ich hab die Version gerade mal ausprobiert, der Log zeigt keine Fehler, aber er verbindet sich trotzdem nicht "mit Gerät oder Dienst".
Hab den von github auch einfach drüber installiert, ohne den alten vorher zu löschen. Wäre das sonst noch ein Versuch wert? 
Hier der log

`2022-09-28 04:57:08.787 - debug: worx.1 (1371536) Plugin sentry destroyed
2022-09-28 04:57:08.788 - info: worx.1 (1371536) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-09-28 04:57:12.589 - debug: worx.1 (1372834) Redis Objects: Use Redis connection: 0.0.0.0:9001
2022-09-28 04:57:12.638 - debug: worx.1 (1372834) Objects client ready ... initialize now
2022-09-28 04:57:12.648 - debug: worx.1 (1372834) Objects create System PubSub Client
2022-09-28 04:57:12.649 - debug: worx.1 (1372834) Objects create User PubSub Client
2022-09-28 04:57:12.754 - debug: worx.1 (1372834) Objects client initialize lua scripts
2022-09-28 04:57:12.757 - debug: worx.1 (1372834) Objects connected to redis: 0.0.0.0:9001
2022-09-28 04:57:12.793 - debug: worx.1 (1372834) Redis States: Use Redis connection: 0.0.0.0:9000
2022-09-28 04:57:12.815 - debug: worx.1 (1372834) States create System PubSub Client
2022-09-28 04:57:12.816 - debug: worx.1 (1372834) States create User PubSub Client
2022-09-28 04:57:12.859 - debug: worx.1 (1372834) States connected to redis: 0.0.0.0:9000
2022-09-28 04:57:13.010 - debug: worx.1 (1372834) Plugin sentry Initialize Plugin (enabled=true)
2022-09-28 04:57:13.306 - info: worx.1 (1372834) starting. Version 1.6.6 (non-npm: iobroker-community-adapters/ioBroker.worx) in /opt/iobroker/node_modules/iobroker.worx, node: v16.17.1, js-controller: 4.0.23
2022-09-28 04:57:13.363 - debug: worx.1 (1372834) Schedule restart: * */23 * * *
2022-09-28 04:57:13.394 - info: worx.1 (1372834) worx is selected`

**Comment by Ilovegym66** [comment]
Hi, Danke TA2k, dass du Dich drum kuemmerst! 
Hier mit Worx das gleiche, die Anmeldung scheint zu gehen, aber es kommen keine Daten, auch keine Fehler.
Das komplette log mit Update:
`
2022-09-28 06:33:27.461  - info: host.Broker3 "system.adapter.worx.0" enabled
2022-09-28 06:33:28.434  - info: host.Broker3 instance system.adapter.worx.0 started with pid 25013
2022-09-28 06:33:33.066  - info: worx.0 (25013) starting. Version 1.6.6 in /opt/iobroker/node_modules/iobroker.worx, node: v16.17.1, js-controller: 4.0.23
2022-09-28 06:33:33.103  - info: worx.0 (25013) worx is selected
2022-09-28 06:33:33.360  - error: worx.0 (25013) Could not Connect to Worx Server: StatusCodeError: 404 - {"message":"Not Found","code":"404.000"}
2022-09-28 06:33:33.361  - error: worx.0 (25013) ERROR: StatusCodeError: 404 - {"message":"Not Found","code":"404.000"}
2022-09-28 06:33:46.867  - info: host.Broker3 "system.adapter.worx.0" disabled
2022-09-28 06:33:46.868  - info: host.Broker3 stopInstance system.adapter.worx.0 (force=false, process=true)
2022-09-28 06:33:46.872  - info: host.Broker3 stopInstance system.adapter.worx.0 send kill signal
2022-09-28 06:33:46.874  - info: worx.0 (25013) Got terminate signal TERMINATE_YOURSELF
2022-09-28 06:33:46.877  - info: worx.0 (25013) cleaned everything up...
2022-09-28 06:33:46.879  - info: worx.0 (25013) terminating
2022-09-28 06:33:46.880  - info: worx.0 (25013) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-09-28 06:33:48.451  - info: host.Broker3 instance system.adapter.worx.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-09-28 06:34:14.214  - info: host.Broker3 Updating repository "Beta (latest)" under "http://download.iobroker.net/sources-dist-latest.json"
2022-09-28 06:35:12.446  - info: host.Broker3 Updating repository "Beta (latest)" under "http://download.iobroker.net/sources-dist-latest.json"
2022-09-28 06:35:45.296  - info: host.Broker3 iobroker url iobroker-community-adapters/ioBroker.worx --host Broker3 --debug
2022-09-28 06:35:49.496  - info: host.Broker3 iobroker install iobroker-community-adapters/ioBroker.worx
2022-09-28 06:35:50.609  - info: host.Broker3 iobroker NPM version: 8.15.0
2022-09-28 06:35:50.613  - info: host.Broker3 iobroker Installing iobroker-community-adapters/ioBroker.worx... (System call)
2022-09-28 06:36:01.160  - info: host.Broker3 iobroker added 9 packages, and changed 2 packages in 9s
2022-09-28 06:36:01.163  - info: host.Broker3 iobroker
2022-09-28 06:36:01.166  - info: host.Broker3 iobroker 25 packages are looking for funding
2022-09-28 06:36:01.169  - info: host.Broker3 iobroker   run `npm fund` for details
2022-09-28 06:36:01.244  - info: host.Broker3 iobroker upload [4] worx.admin /opt/iobroker/node_modules/iobroker.worx/admin/index_m.html index_m.html text/html
2022-09-28 06:36:03.267  - info: host.Broker3 iobroker upload [3] worx.admin /opt/iobroker/node_modules/iobroker.worx/admin/style.css style.css text/css
2022-09-28 06:36:03.275  - info: host.Broker3 iobroker upload [2] worx.admin /opt/iobroker/node_modules/iobroker.worx/admin/words.js words.js application/javascript
2022-09-28 06:36:03.285  - info: host.Broker3 iobroker upload [1] worx.admin /opt/iobroker/node_modules/iobroker.worx/admin/worx.png worx.png image/png
2022-09-28 06:36:03.295  - info: host.Broker3 iobroker upload [0] worx.admin /opt/iobroker/node_modules/iobroker.worx/admin/worx_ada2.png worx_ada2.png image/png
2022-09-28 06:36:04.073  - info: host.Broker3 iobroker Update "system.adapter.worx.0"
2022-09-28 06:36:05.115  - info: host.Broker3 iobroker exit 0
2022-09-28 06:36:32.569  - info: host.Broker3 "system.adapter.worx.0" enabled
2022-09-28 06:36:33.599  - info: host.Broker3 instance system.adapter.worx.0 started with pid 25751
2022-09-28 06:36:37.872  - info: worx.0 (25751) starting. Version 1.6.6 (non-npm: iobroker-community-adapters/ioBroker.worx) in /opt/iobroker/node_modules/iobroker.worx, node: v16.17.1, js-controller: 4.0.23
2022-09-28 06:36:37.908  - info: worx.0 (25751) worx is selected
2022-09-28 06:38:00.047  - info: host.Broker3 stopInstance system.adapter.worx.0 (force=false, process=true)
2022-09-28 06:38:00.054  - info: worx.0 (25751) Got terminate signal TERMINATE_YOURSELF
2022-09-28 06:38:00.055  - info: worx.0 (25751) cleaned everything up...
2022-09-28 06:38:00.057  - info: worx.0 (25751) terminating
2022-09-28 06:38:00.059  - info: worx.0 (25751) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-09-28 06:38:00.079  - info: host.Broker3 stopInstance system.adapter.worx.0 send kill signal
2022-09-28 06:38:01.628  - info: host.Broker3 instance system.adapter.worx.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-09-28 06:38:03.888  - info: host.Broker3 instance system.adapter.worx.0 started with pid 25766
2022-09-28 06:38:05.724  - debug: worx.0 (25766) Redis Objects: Use Redis connection: 192.168.3.41:6379
2022-09-28 06:38:05.830  - debug: worx.0 (25766) Objects client ready ... initialize now
2022-09-28 06:38:05.833  - debug: worx.0 (25766) Objects create System PubSub Client
2022-09-28 06:38:05.835  - debug: worx.0 (25766) Objects create User PubSub Client
2022-09-28 06:38:06.918  - debug: worx.0 (25766) Objects client initialize lua scripts
2022-09-28 06:38:06.927  - debug: worx.0 (25766) Objects connected to redis: 192.168.3.41:6379
2022-09-28 06:38:07.687  - debug: worx.0 (25766) Redis States: Use Redis connection: 192.168.3.41:6379
2022-09-28 06:38:07.695  - debug: worx.0 (25766) States create System PubSub Client
2022-09-28 06:38:07.697  - debug: worx.0 (25766) States create User PubSub Client
2022-09-28 06:38:07.707  - debug: worx.0 (25766) States connected to redis: 192.168.3.41:6379
2022-09-28 06:38:07.841  - debug: worx.0 (25766) Plugin sentry Initialize Plugin (enabled=true)
2022-09-28 06:38:08.241  - info: worx.0 (25766) starting. Version 1.6.6 (non-npm: iobroker-community-adapters/ioBroker.worx) in /opt/iobroker/node_modules/iobroker.worx, node: v16.17.1, js-controller: 4.0.23
2022-09-28 06:38:08.282  - info: worx.0 (25766) worx is selected

`

**Comment by nikmaier** [comment]
Hi, gleiche bei mir, habe auch die Git Version drüberinstalliert, kommt auch kein Fehler, aber verbindet sich leider nicht:


![git1](https://user-images.githubusercontent.com/69574329/192704044-006d4e0b-7ebc-42b8-852f-b411f55d2d1a.png)

**Comment by TA2k** [comment]
Jetzt sollte auch in der GitHub version was passieren.

**Comment by nikmaier** [comment]
@TA2k 
Geht bei mir leider noch nicht, aber jetzt passiert was im Log:

`<html><body>


2022-09-28 08:51:44.652  - info: host.IOBROKER(SmartHome) "system.adapter.worx.0" enabled
--
2022-09-28 08:51:44.770  - info: host.IOBROKER(SmartHome) instance system.adapter.worx.0 started with pid 24028
2022-09-28 08:51:46.584  - info:  worx.0 (24028) starting. Version 1.6.6 (non-npm:  iobroker-community-adapters/ioBroker.worx) in  C:/iobroker/SmartHome/node_modules/iobroker.worx, node: v14.19.3,  js-controller: 4.0.23
2022-09-28 08:51:46.595  - info: worx.0 (24028) worx is selected
2022-09-28 08:51:48.361  - info: worx.0 (24028) Connect to worx ok
2022-09-28 08:51:49.144  - error:  worx.0 (24028) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-09-28 08:51:49.144  - error:  worx.0 (24028) unhandled promise rejection: 405 - {"message":"The GET  method is not supported for this route. Supported methods: POST."}
2022-09-28 08:51:49.144  - error: worx.0 (24028) StatusCodeError: 405 - {"message":"The GET method is not supported for this route. Supported methods: POST."}
at new StatusCodeError (C:\iobroker\SmartHome\node_modules\request-promise-core\lib\errors.js:32:15)
at Request.plumbing.callback (C:\iobroker\SmartHome\node_modules\request-promise-core\lib\plumbing.js:104:33)
at Request.RP$callback [as _callback] (C:\iobroker\SmartHome\node_modules\request-promise-core\lib\plumbing.js:46:31)
at Request.self.callback (C:\iobroker\SmartHome\node_modules\request\request.js:185:22)
at Request.emit (events.js:400:28)
at Request.emit (domain.js:475:12)
at Request. (C:\iobroker\SmartHome\node_modules\request\request.js:1161:10)
at Request.emit (events.js:400:28)
at Request.emit (domain.js:475:12)
at IncomingMessage. (C:\iobroker\SmartHome\node_modules\request\request.js:1083:12)
at Object.onceWrapper (events.js:519:28)
at IncomingMessage.emit (events.js:412:35)
at IncomingMessage.emit (domain.js:475:12)
at endReadableNT (internal/streams/readable.js:1333:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-09-28 08:51:49.145  - error: worx.0 (24028) 405 - {"message":"The GET method is not supported for this route. Supported methods: POST."}
2022-09-28 08:51:49.153  - info: worx.0 (24028) cleaned everything up...
2022-09-28 08:51:49.153  - info: worx.0 (24028) terminating
2022-09-28 08:51:49.154  - warn: worx.0 (24028) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-09-28 08:51:49.195  - error: worx.0 (24028) MQTT ERROR: Error: client disconnecting
2022-09-28 08:51:49.195  - error: worx.0 (24028) MQTT ERROR: Error: client disconnecting
2022-09-28 08:51:49.933  - error:  host.IOBROKER(SmartHome) Caught by controller[0]: This error originated  either by throwing inside of an async function without a catch block,  or by rejecting a promise which was not handled with .catch(). The  promise rejected with the reason:
2022-09-28 08:51:49.933  - error:  host.IOBROKER(SmartHome) Caught by controller[1]: StatusCodeError: 405 -  {"message":"The GET method is not supported for this route. Supported  methods: POST."}
2022-09-28 08:51:49.933  - error:  host.IOBROKER(SmartHome) Caught by controller[1]:     at new  StatusCodeError  (C:\iobroker\SmartHome\node_modules\request-promise-core\lib\errors.js:32:15)
2022-09-28 08:51:49.933  - error:  host.IOBROKER(SmartHome) Caught by controller[1]:     at  Request.plumbing.callback  (C:\iobroker\SmartHome\node_modules\request-promise-core\lib\plumbing.js:104:33)
2022-09-28 08:51:49.933  - error:  host.IOBROKER(SmartHome) Caught by controller[1]:     at  Request.RP$callback [as _callback]  (C:\iobroker\SmartHome\node_modules\request-promise-core\lib\plumbing.js:46:31)
2022-09-28 08:51:49.933  - error:  host.IOBROKER(SmartHome) Caught by controller[1]:     at  Request.self.callback  (C:\iobroker\SmartHome\node_modules\request\request.js:185:22)
2022-09-28 08:51:49.933  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at Request.emit (events.js:400:28)
2022-09-28 08:51:49.933  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at Request.emit (domain.js:475:12)
2022-09-28 08:51:49.933  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at Request. (C:\iobroker\SmartHome\node_modules\request\request.js:1161:10)
2022-09-28 08:51:49.934  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at Request.emit (events.js:400:28)
2022-09-28 08:51:49.934  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at Request.emit (domain.js:475:12)
2022-09-28 08:51:49.934  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at IncomingMessage. (C:\iobroker\SmartHome\node_modules\request\request.js:1083:12)
2022-09-28 08:51:49.934  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at Object.onceWrapper (events.js:519:28)
2022-09-28 08:51:49.934  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at IncomingMessage.emit (events.js:412:35)
2022-09-28 08:51:49.934  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at IncomingMessage.emit (domain.js:475:12)
2022-09-28 08:51:49.934  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at endReadableNT (internal/streams/readable.js:1333:12)
2022-09-28 08:51:49.934  - error: host.IOBROKER(SmartHome) Caught by controller[1]:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-09-28 08:51:49.934  - error: host.IOBROKER(SmartHome) instance system.adapter.worx.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-09-28 08:51:49.934  - info: host.IOBROKER(SmartHome) Restart adapter system.adapter.worx.0 because enabled
2022-09-28 08:52:20.022  - info: host.IOBROKER(SmartHome) instance system.adapter.worx.0 started with pid 23216
2022-09-28 08:52:21.724  - info:  worx.0 (23216) starting. Version 1.6.6 (non-npm:  iobroker-community-adapters/ioBroker.worx) in  C:/iobroker/SmartHome/node_modules/iobroker.worx, node: v14.19.3,  js-controller: 4.0.23
2022-09-28 08:52:21.734  - info: worx.0 (23216) worx is selected
2022-09-28 08:52:23.481  - info: worx.0 (23216) Connect to worx ok
2022-09-28 08:52:24.242  - error:  worx.0 (23216) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-09-28 08:52:24.242  - error:  worx.0 (23216) unhandled promise rejection: 405 - {"message":"The GET  method is not supported for this route. Supported methods: POST."}
2022-09-28 08:52:24.243  - error: worx.0 (23216) StatusCodeError: 405 - {"message":"The GET method is not supported for this route. Supported methods: POST."}
at new StatusCodeError (C:\iobroker\SmartHome\node_modules\request-promise-core\lib\errors.js:32:15)
at Request.plumbing.callback (C:\iobroker\SmartHome\node_modules\request-promise-core\lib\plumbing.js:104:33)
at Request.RP$callback [as _callback] (C:\iobroker\SmartHome\node_modules\request-promise-core\lib\plumbing.js:46:31)
at Request.self.callback (C:\iobroker\SmartHome\node_modules\request\request.js:185:22)
at Request.emit (events.js:400:28)
at Request.emit (domain.js:475:12)
at Request. (C:\iobroker\SmartHome\node_modules\request\request.js:1161:10)
at Request.emit (events.js:400:28)
at Request.emit (domain.js:475:12)
at IncomingMessage. (C:\iobroker\SmartHome\node_modules\request\request.js:1083:12)
at Object.onceWrapper (events.js:519:28)
at IncomingMessage.emit (events.js:412:35)
at IncomingMessage.emit (domain.js:475:12)
at endReadableNT (internal/streams/readable.js:1333:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-09-28 08:52:24.243  - error: worx.0 (23216) 405 - {"message":"The GET method is not supported for this route. Supported methods: POST."}
2022-09-28 08:52:24.249  - info: worx.0 (23216) cleaned everything up...
2022-09-28 08:52:24.251  - info: worx.0 (23216) terminating
2022-09-28 08:52:24.251  - warn: worx.0 (23216) Terminated (UNCAUGHT_EXCEPTION): Without reason


</body>
</html>`

P.S. Vielen Dank für deine Bemühungen.

**Comment by TA2k** [comment]
Sollte jetzt besser laufen

**Comment by Ilovegym66** [comment]
yep, super! laeuft!

**Comment by nikmaier** [comment]
Jawoll, es funktioniert wieder alles!
Du bist echt der Beste, was du leistest ist echt super (nicht nur bei dem Adapter, auch beim VW Connect Adapter usw.) TOP!

Vielen Dank.

**Comment by Semmy100** [comment]
Funktioniert denn dann auch wieder die Verbindung zu Kress?

**Comment by MubiTec** [comment]
Geht auch bei mir wieder, ganz vielen Dank!

**Comment by TA2k** [comment]
Kress und landscape sollte jetzt auch gehen ist aber ungerüstet

**Comment by Semmy100** [comment]
Kress geht noch nicht

**Comment by Semmy100** [comment]
Das ist der Log-Eintrag:
<html>
<body>


worx.0 | 2022-09-28 14:40:18.421 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
worx.0 | 2022-09-28 14:40:18.421 | debug | Plugin sentry destroyed
worx.0 | 2022-09-28 14:40:18.419 | info | terminating
worx.0 | 2022-09-28 14:40:18.418 | info | cleaned everything up...
worx.0 | 2022-09-28 14:40:18.323 | error | Exception-Code: ERR_BAD_REQUEST: Request failed with status code 400
worx.0 | 2022-09-28 14:40:18.322 | error | unhandled promise rejection: Request failed with status code 400
worx.0 | 2022-09-28 14:40:18.321 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
worx.0 | 2022-09-28 14:40:18.319 | error | AxiosError: Request failed with status code 400
worx.0 | 2022-09-28 14:40:16.727 | info | Connect to kress
worx.0 | 2022-09-28 14:40:16.725 | info | kress is selected
worx.0 | 2022-09-28 14:40:16.684 | info | starting. Version 1.6.6 (non-npm: iobroker-community-adapters/ioBroker.worx#add2a2836fab8513ad7310432eaca273922dbe09) in /opt/iobroker/node_modules/iobroker.worx, node: v16.17.1, js-controller: 4.0.23
worx.0 | 2022-09-28 14:40:16.135 | debug | Plugin sentry Initialize Plugin (enabled=true)


</body>
</html>

**Comment by Semmy100** [comment]
<html>
<body>


worx.0 | 2022-09-28 16:46:36.097 | warn | Could not get code response
-- | -- | -- | --
worx.0 | 2022-09-28 16:46:36.096 | error | AxiosError: Request failed with status code 419
worx.0 | 2022-09-28 16:46:35.842 | error | TypeError: Cannot read properties of undefined (reading 'adapter')
worx.0 | 2022-09-28 16:46:35.101 | info | Connect to kress
worx.0 | 2022-09-28 16:46:35.099 | info | kress is selected
worx.0 | 2022-09-28 16:46:35.060 | info | starting. Version 1.6.6 (non-npm: iobroker-community-adapters/ioBroker.worx) in /opt/iobroker/node_modules/iobroker.worx, node: v16.17.1, js-controller: 4.0.23
worx.0 | 2022-09-28 16:46:34.537 | debug | Plugin sentry Initialize Plugin (enabled=true)
worx.0 | 2022-09-28 16:46:34.255 | debug | States connected to redis: 127.0.0.1:9000
worx.0 | 2022-09-28 16:46:34.087 | debug | States create User PubSub Client
worx.0 | 2022-09-28 16:46:34.084 | debug | States create System PubSub Client
worx.0 | 2022-09-28 16:46:34.031 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
worx.0 | 2022-09-28 16:46:33.954 | debug | Objects connected to redis: 127.0.0.1:9001
worx.0 | 2022-09-28 16:46:33.945 | debug | Objects client initialize lua scripts
worx.0 | 2022-09-28 16:46:33.780 | debug | Objects create User PubSub Client
worx.0 | 2022-09-28 16:46:33.778 | debug | Objects create System PubSub Client
worx.0 | 2022-09-28 16:46:33.776 | debug | Objects client ready ... initialize now
worx.0 | 2022-09-28 16:46:33.692 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
worx.0 | 2022-09-28 16:46:28.423 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
worx.0 | 2022-09-28 16:46:28.423 | debug | Plugin sentry destroyed
worx.0 | 2022-09-28 16:46:28.421 | info | terminating
worx.0 | 2022-09-28 16:46:28.420 | info | cleaned everything up...
worx.0 | 2022-09-28 16:46:28.415 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>

**Comment by TA2k** [comment]
Bitte nochmal probieren

**Comment by Semmy100** [comment]
<html>
<body>


worx.0 | 2022-09-28 16:59:51.026 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
worx.0 | 2022-09-28 16:59:51.026 | debug | Plugin sentry destroyed
worx.0 | 2022-09-28 16:59:51.025 | info | terminating
worx.0 | 2022-09-28 16:59:51.023 | info | cleaned everything up...
worx.0 | 2022-09-28 16:59:50.950 | error | Exception-Code: ERR_BAD_REQUEST: Request failed with status code 400
worx.0 | 2022-09-28 16:59:50.950 | error | unhandled promise rejection: Request failed with status code 400
worx.0 | 2022-09-28 16:59:50.949 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
worx.0 | 2022-09-28 16:59:50.947 | error | {"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","hint":"Check the `code` parameter","message":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."}
worx.0 | 2022-09-28 16:59:50.947 | error | AxiosError: Request failed with status code 400
worx.0 | 2022-09-28 16:59:50.704 | error | Login form submission failed
worx.0 | 2022-09-28 16:59:50.107 | info | Login form loaded
worx.0 | 2022-09-28 16:59:49.428 | info | Connect to kress
worx.0 | 2022-09-28 16:59:49.426 | info | kress is selected
worx.0 | 2022-09-28 16:59:49.383 | info | starting. Version 1.6.6 (non-npm: iobroker-community-adapters/ioBroker.worx) in /opt/iobroker/node_modules/iobroker.worx, node: v16.17.1, js-controller: 4.0.23
worx.0 | 2022-09-28 16:59:48.794 | debug | Plugin sentry Initialize Plugin (enabled=true)


</body>
</html>

**Comment by TA2k** [comment]
Ich vermute das Passwort ist falsch aber installiere nochmal dann sollten mehr infos kommen

**Comment by TA2k** [comment]
Ja scheint als wäre email oder Passwort falsch.
Einfach nochmal eingeben

**Comment by Semmy100** [comment]
Funktioniert noch nicht, habe bei der Instanz 2 grüne und ein rotes Feld. Kann es sein, dass für das Passwort keine Symbole funktionieren?

**Comment by Semmy100** [comment]
Ok, ich habe mal Symbole weg gelassen und nun funktioniert es auch bei mir. Vielen Dank an alle.

Gruß
Semmy

**Comment by TA2k** [comment]
Bitte mal die aktuelle GitHub mit Sonderzeichen im Passwort probieren ob das jetzt

**Comment by Semmy100** [comment]
Super, funktioniert jetzt auch mit Sonderzeichen.
